/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Coils_X_aliases.h"
#include "Coils_X.h"
#include "Coils_Y_aliases.h"
#include "Coils_Y.h"
#include "MOSI_1_aliases.h"
#include "MOSI_1.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "SPIS_1.h"
#include "SPIS_1_PVT.h"
#include "SS_1_aliases.h"
#include "SS_1.h"
#include "isr_1.h"
#include "Pin_X_aliases.h"
#include "Pin_X.h"
#include "ADC_SAR_Seq.h"
#include "Pin_int_x_aliases.h"
#include "Pin_int_x.h"
#include "Pin_Y_aliases.h"
#include "Pin_Y.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "MotorOut_1_aliases.h"
#include "MotorOut_1.h"
#include "stepindex_1.h"
#include "pwm_isr_1.h"
#include "PWM_2.h"
#include "Enable_1_aliases.h"
#include "Enable_1.h"
#include "Clock_2.h"
#include "MotorOut_2_aliases.h"
#include "MotorOut_2.h"
#include "stepindex_2.h"
#include "pwm_isr_2.h"
#include "Enable_2_aliases.h"
#include "Enable_2.h"
#include "Pin_int_y_aliases.h"
#include "Pin_int_y.h"
#include "isr_x.h"
#include "isr_y.h"
#include "SPIS_1_IntClock.h"
#include "ADC_SAR_Seq_SAR.h"
#include "ADC_SAR_Seq_IntClock.h"
#include "ADC_SAR_Seq_TempBuf_dma.h"
#include "ADC_SAR_Seq_FinalBuf_dma.h"
#include "ADC_SAR_Seq_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

