/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "isr_RxD.h"
#include "Coils_Y_aliases.h"
#include "Coils_Y.h"
#include "ADC_SAR_Seq.h"
#include "Pin_X_aliases.h"
#include "Pin_X.h"
#include "Coils_X_aliases.h"
#include "Coils_X.h"
#include "Pin_int_x_aliases.h"
#include "Pin_int_x.h"
#include "isr_y.h"
#include "Pin_Y_aliases.h"
#include "Pin_Y.h"
#include "isr_x.h"
#include "Pin_int_y_aliases.h"
#include "Pin_int_y.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_Seq_SAR.h"
#include "ADC_SAR_Seq_IntClock.h"
#include "ADC_SAR_Seq_TempBuf_dma.h"
#include "ADC_SAR_Seq_FinalBuf_dma.h"
#include "ADC_SAR_Seq_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

