/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MOSI_1_aliases.h"
#include "MOSI_1.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "MISO_1_aliases.h"
#include "MISO_1.h"
#include "SS_1_aliases.h"
#include "SS_1.h"
#include "isr_1.h"
#include "SPIS_1.h"
#include "SPIS_1_PVT.h"
#include "PWM_1.h"
#include "Step_1_aliases.h"
#include "Step_1.h"
#include "Enable_1_aliases.h"
#include "Enable_1.h"
#include "Direction_1_aliases.h"
#include "Direction_1.h"
#include "pwm_isr_1.h"
#include "Clock_1.h"
#include "SPIS_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

